ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymb = ', MDL_YMB
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_ymtau = ', MDL_YMTAU
      WRITE(*,*) 'mdl_xi = ', MDL_XI
      WRITE(*,*) 'mdl_grhopWZ = ', MDL_GRHOPWZ
      WRITE(*,*) 'mdl_grhopWh = ', MDL_GRHOPWH
      WRITE(*,*) 'mdl_grhopud = ', MDL_GRHOPUD
      WRITE(*,*) 'mdl_grhoptb = ', MDL_GRHOPTB
      WRITE(*,*) 'mdl_grhopT23LbL = ', MDL_GRHOPT23LBL
      WRITE(*,*) 'mdl_grhopX23LbL = ', MDL_GRHOPX23LBL
      WRITE(*,*) 'mdl_grhopX53LX23L = ', MDL_GRHOPX53LX23L
      WRITE(*,*) 'mdl_grhopX53RX23R = ', MDL_GRHOPX53RX23R
      WRITE(*,*) 'mdl_grhopX53LtL = ', MDL_GRHOPX53LTL
      WRITE(*,*) 'mdl_grhopX53RtR = ', MDL_GRHOPX53RTR
      WRITE(*,*) 'mdl_grhopX53LT23L = ', MDL_GRHOPX53LT23L
      WRITE(*,*) 'mdl_grhopX53RT23R = ', MDL_GRHOPX53RT23R
      WRITE(*,*) 'mdl_grhopT23LB13L = ', MDL_GRHOPT23LB13L
      WRITE(*,*) 'mdl_grhopT23RB13R = ', MDL_GRHOPT23RB13R
      WRITE(*,*) 'mdl_grhoptLB13L = ', MDL_GRHOPTLB13L
      WRITE(*,*) 'mdl_grhoptRB13R = ', MDL_GRHOPTRB13R
      WRITE(*,*) 'mdl_grhopX23LB13L = ', MDL_GRHOPX23LB13L
      WRITE(*,*) 'mdl_grhopX23RB13R = ', MDL_GRHOPX23RB13R
      WRITE(*,*) 'mdl_grho0WW = ', MDL_GRHO0WW
      WRITE(*,*) 'mdl_grho0Zh = ', MDL_GRHO0ZH
      WRITE(*,*) 'mdl_grho0ffL = ', MDL_GRHO0FFL
      WRITE(*,*) 'mdl_grho0ffY = ', MDL_GRHO0FFY
      WRITE(*,*) 'mdl_grho0ttL = ', MDL_GRHO0TTL
      WRITE(*,*) 'mdl_grho0bbL = ', MDL_GRHO0BBL
      WRITE(*,*) 'mdl_grho0ttR = ', MDL_GRHO0TTR
      WRITE(*,*) 'mdl_grho0bbR = ', MDL_GRHO0BBR
      WRITE(*,*) 'mdl_grho0X53LX53L = ', MDL_GRHO0X53LX53L
      WRITE(*,*) 'mdl_grho0X53RX53R = ', MDL_GRHO0X53RX53R
      WRITE(*,*) 'mdl_grho0X23LX23L = ', MDL_GRHO0X23LX23L
      WRITE(*,*) 'mdl_grho0X23RX23R = ', MDL_GRHO0X23RX23R
      WRITE(*,*) 'mdl_grho0X23LtL = ', MDL_GRHO0X23LTL
      WRITE(*,*) 'mdl_grho0X23RtR = ', MDL_GRHO0X23RTR
      WRITE(*,*) 'mdl_grho0X23LT23L = ', MDL_GRHO0X23LT23L
      WRITE(*,*) 'mdl_grho0X23RT23R = ', MDL_GRHO0X23RT23R
      WRITE(*,*) 'mdl_grho0T23LT23L = ', MDL_GRHO0T23LT23L
      WRITE(*,*) 'mdl_grho0T23RT23R = ', MDL_GRHO0T23RT23R
      WRITE(*,*) 'mdl_grho0T23LtL = ', MDL_GRHO0T23LTL
      WRITE(*,*) 'mdl_grho0T23RtR = ', MDL_GRHO0T23RTR
      WRITE(*,*) 'mdl_grho0B13LB13L = ', MDL_GRHO0B13LB13L
      WRITE(*,*) 'mdl_grho0B13RB13R = ', MDL_GRHO0B13RB13R
      WRITE(*,*) 'mdl_grhoprhomZ = ', MDL_GRHOPRHOMZ
      WRITE(*,*) 'mdl_grhopWmrho0 = ', MDL_GRHOPWMRHO0
      WRITE(*,*) 'mdl_grhoprhomrho0 = ', MDL_GRHOPRHOMRHO0
      WRITE(*,*) 'mdl_ghWW = ', MDL_GHWW
      WRITE(*,*) 'mdl_ghZZ = ', MDL_GHZZ
      WRITE(*,*) 'mdl_ghhWW = ', MDL_GHHWW
      WRITE(*,*) 'mdl_ghhZZ = ', MDL_GHHZZ
      WRITE(*,*) 'mdl_gWT23LbL = ', MDL_GWT23LBL
      WRITE(*,*) 'mdl_gWX23LbL = ', MDL_GWX23LBL
      WRITE(*,*) 'mdl_gWtLB13L = ', MDL_GWTLB13L
      WRITE(*,*) 'mdl_gWtRB13R = ', MDL_GWTRB13R
      WRITE(*,*) 'mdl_gWX53LtL = ', MDL_GWX53LTL
      WRITE(*,*) 'mdl_gWX53RtR = ', MDL_GWX53RTR
      WRITE(*,*) 'mdl_gZT23LtL = ', MDL_GZT23LTL
      WRITE(*,*) 'mdl_gZT23RtR = ', MDL_GZT23RTR
      WRITE(*,*) 'mdl_gZX23LtL = ', MDL_GZX23LTL
      WRITE(*,*) 'mdl_gZX23RtR = ', MDL_GZX23RTR
      WRITE(*,*) 'mdl_ghT23LtR = ', MDL_GHT23LTR
      WRITE(*,*) 'mdl_ghtLT23R = ', MDL_GHTLT23R
      WRITE(*,*) 'mdl_ghX23LtR = ', MDL_GHX23LTR
      WRITE(*,*) 'mdl_ghtLX23R = ', MDL_GHTLX23R
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_MH = ', MDL_MH
      WRITE(*,*) 'mdl_mrhop = ', MDL_MRHOP
      WRITE(*,*) 'mdl_mrho0 = ', MDL_MRHO0
      WRITE(*,*) 'mdl_MT23 = ', MDL_MT23
      WRITE(*,*) 'mdl_MB13 = ', MDL_MB13
      WRITE(*,*) 'mdl_MX53 = ', MDL_MX53
      WRITE(*,*) 'mdl_MX23 = ', MDL_MX23
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*) 'mdl_wrhop = ', MDL_WRHOP
      WRITE(*,*) 'mdl_wrho0 = ', MDL_WRHO0
      WRITE(*,*) 'mdl_WT23 = ', MDL_WT23
      WRITE(*,*) 'mdl_WB13 = ', MDL_WB13
      WRITE(*,*) 'mdl_WX53 = ', MDL_WX53
      WRITE(*,*) 'mdl_WX23 = ', MDL_WX23
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_MH__exp__2 = ', MDL_MH__EXP__2
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_sw2 = ', MDL_SW2
      WRITE(*,*) 'mdl_cw = ', MDL_CW
      WRITE(*,*) 'mdl_sqrt__sw2 = ', MDL_SQRT__SW2
      WRITE(*,*) 'mdl_sw = ', MDL_SW
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_vev = ', MDL_VEV
      WRITE(*,*) 'mdl_vev__exp__2 = ', MDL_VEV__EXP__2
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_yb = ', MDL_YB
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_ytau = ', MDL_YTAU
      WRITE(*,*) 'mdl_muH = ', MDL_MUH
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_sw__exp__2 = ', MDL_SW__EXP__2
      WRITE(*,*) 'mdl_cw__exp__2 = ', MDL_CW__EXP__2
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
