C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA (IFOREST(I,-1,1),I=1,2)/4,3/
      DATA (SPROP(I,-1,1),I=1,2)/-8000001,-8000001/
      DATA TPRID(-1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/5,-1/
      DATA (SPROP(I,-2,1),I=1,2)/-9900213,-9900213/
      DATA TPRID(-2,1)/0/
      DATA (IFOREST(I,-3,1),I=1,2)/6,-2/
      DATA (SPROP(I,-3,1),I=1,2)/1,-2/
      DATA TPRID(-3,1)/0/
C     Diagram 2
      DATA MAPCONFIG(2)/2/
      DATA (IFOREST(I,-1,2),I=1,2)/4,3/
      DATA (SPROP(I,-1,2),I=1,2)/-8000001,-8000001/
      DATA TPRID(-1,2)/0/
      DATA (IFOREST(I,-2,2),I=1,2)/5,-1/
      DATA (SPROP(I,-2,2),I=1,2)/-9900213,-9900213/
      DATA TPRID(-2,2)/0/
      DATA (IFOREST(I,-3,2),I=1,2)/1,6/
      DATA TPRID(-3,2)/2/
      DATA (SPROP(I,-3,2),I=1,2)/0,0/
      DATA (IFOREST(I,-4,2),I=1,2)/-3,-2/
C     Number of configs
      DATA MAPCONFIG(0)/2/
