ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of onerho'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_44 = ', GC_44
      WRITE(*,2) 'GC_49 = ', GC_49
      WRITE(*,2) 'GC_64 = ', GC_64
